version: '3.8'

services:
  youtrack:
    image: jetbrains/youtrack:2024.1.29548
    restart: always
    environment:
      - DATABASE_PATH=/opt/youtrack/data
      - JAVA_OPTS=-Xmx1g
    ports:
      - '80:8080'

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
      MINIO_DEFAULT_BUCKETS: sample
    command: server /data --console-address ":9001"
    ports:
      - "8080:9000"
      - "5000:9001"


  clamav:
    image: clamav/clamav:latest
    restart: always
    ports:
      - "3310:3310"
    command: [
      "clamd",
      "--foreground=true",
      "--config-file=/etc/clamav/clamd.conf"
